services:
  postgres-db:
    image: postgres:17.6
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - restweb-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  restweb-postgres-data:
